### ISSUE TITLE
how to deploy locally?

### ISSUE THREAD

**Issue by joamatab** [sebst/pythonic-news#10]
Here are the steps I followed in ubuntu18 python3.6.8:

```
python -m venv venv
source venv/bin/activate
python manage.py migrate
python manage.py runserver
```
In hnclone/settings.py i changed:
```
ACCEPT_UNINVITED_REGISTRATIONS = True
```

When I hit register I see 
```
Server Error (500)
```

**Comment by sebst** [comment]
Most likely you need to install the requirements from requirements.txt.

Turn DEBUG=True in settings.py and you should see a detailed error message.

**Comment by sebst** [comment]
#12
