### ISSUE TITLE
add RSS feed

### ISSUE THREAD

**Issue by bbelderbos** [sebst/pythonic-news#7]
Seems commented in the source, would be nice for parsing / automation (e.g. send email digest of top commented/voted links)

**Comment by sebst** [comment]
Now, there are two RSS feeds:

https://news.python.sc/newest/feed/  -- for the "newest" stories
https://news.python.sc/feed/ -- for the front page stories

**Comment by bbelderbos** [comment]
Awesome, thanks @sebst 

We added an exercise the other day to scrape a static copy of the site: https://codechalleng.es/bites/promo/news.python.sc 

I also added a script to email a digest every week based on max upvotes/comments to keep up with the news (using the code of mentioned exercise). 

I wanted to refactor the `BeautifulSoup` code to use `feedparser` to not rely on potentially changing template HTML, but I don't see upvotes/comment counts in the feed. Would it be easy to add those please? 

Thanks for this site!

**Comment by pintman** [comment]
> I also added a script to email a digest every week based on max upvotes/comments to keep up with the news (using the code of mentioned exercise).

I hope that this 'feature' is opt in. Otherwise it's not GDPR compliant in the EU.

**Comment by bbelderbos** [comment]
Yes this is opt in, why is it not GDPR compliant?

**Comment by pintman** [comment]
Bob Belderbos schrieb am 22.10.19 um 09:42:
> Yes this is opt in,

Great to hear that. :)

> why is it not GDPR compliant?

They didn't know in advance what their email address was used for.
